name: flutter_stateman
description: Flutter StateManager is a simple state management and IoC library for Dart and Flutter.
version: 0.0.6
homepage: https://github.com/cbalmeida/stateman

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: